language: java
jdk: oraclejdk8
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f575727d0541_key -iv $encrypted_f575727d0541_iv
  -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d
- chmod 600 /tmp/travis_deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/travis_deploy_rsa
- echo -e "Host $SERVER_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sudo service mysql stop
- docker pull takimatraining/devops-training-db
- docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db
script:
- |
  mvn clean install sonar:sonar \
  -Dsonar.projectKey=<SONAR_PROJECT_KEY> \
  -Dsonar.organization=<SONAR_ORGANISATION_KEY> \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=$SONAR_TOKEN

# Deploy updated container over ssh
deploy:
  provider: script
  script: ssh -i /tmp/travis_deploy_rsa $DEPLOY_USER@$SERVER_HOST "sudo docker pull $IMAGE_NAME:$TAG && sudo docker rm -f app || true && sudo docker run -d --network net -p 80:8080 --name app $IMAGE_NAME:$TAG"
  on:
    branch: master

cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: "<ENCRYPTED_TOKEN>"
notifications:
  email:
    on_failure: always
